# Generated by Django 5.1.7 on 2025-04-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignForm',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='signform_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='signform_users', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('concession_id', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=255)),
                ('collegename', models.CharField(max_length=255)),
                ('station1', models.CharField(max_length=100)),
                ('station2', models.CharField(max_length=100)),
                ('travel_class', models.CharField(max_length=50)),
                ('validity', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months')])),
                ('current_date', models.DateField()),
                ('valid_till_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('under_process_date', models.DateField(blank=True, default=None, null=True)),
                ('accepted_date', models.DateField(blank=True, default=None, null=True)),
                ('rejected_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_process', 'Under Process'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('concession_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concession.details')),
            ],
        ),
    ]
