# Generated by Django 5.1.7 on 2025-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contrast_mode',
            field=models.CharField(choices=[('default', 'Default'), ('high', 'High Contrast')], default='default', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10, null=True),
        ),
    ]
