# Generated by Django 5.1.7 on 2025-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0004_alter_userprofile_contrast_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contrast_mode',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('high', 'High Contrast')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='font_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
