# Generated by Django 5.1.7 on 2025-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0005_alter_userprofile_contrast_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signform',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
